Repository dnd-side-project/dnd-mentee-4th-9-repo, pull requests merged in 2021-02, with the labels that each got.

#26 Feat add prettier setting
  frontend/.prettierrc
  frontend/package.json
  frontend/src/App.tsx
  frontend/yarn.lock
Labels: FE, documentation

#24 add serverless.yml for deploying s3 bucket for public & static media
  backend/serverless.yml
Labels: BE, enhancement

#30 [feat] Set page routing
  frontend/.gitignore
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Nav/Nav.jsx
  frontend/src/views/Error.jsx
  frontend/src/views/Home.jsx
  frontend/src/views/Plants.jsx
  frontend/src/views/PlantsDetail.jsx
  frontend/src/views/Subscription.jsx
  frontend/src/views/Test.jsx
  frontend/src/views/TestResult.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#36 [feat] Add Button component and theme properties
  frontend/src/index.tsx
  frontend/src/lib/calculate.js
  frontend/src/styles/Button.js
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/theme.js
Labels: FE, enhancement

#33 [feat] add plant & tag model classes and controllers
  backend/controllers/plant.controller.js
  backend/models/index.js
  backend/models/plant.model.js
  backend/models/tag.model.js
  backend/routes/plants.route.js
Labels: BE, enhancement

#38 Feature/front/recommend plant
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/TagList.jsx
Labels: FE, enhancement

#41 [feat] remove likes field in Plant model
  backend/models/plant.model.js
Labels: BE, enhancement

#42 [feat] query without junction table's attributes
  backend/controllers/plant.controller.js
Labels: BE, enhancement

#43 Feature/front/footer
  frontend/public/images/logo_footer.png
  frontend/public/index.html
  frontend/src/components/Footer/Contact.jsx
  frontend/src/components/Footer/Corp.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/Item.jsx
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/theme.js
  frontend/src/views/Home.jsx
  frontend/src/views/TestResult.jsx
Labels: FE, enhancement

#40 [feat] add setup.js for reseting & adding seed data in database tables.
  backend/models/index.js
  backend/models/plant.model.js
  backend/models/tag.model.js
  backend/setup.js
Labels: BE, enhancement

#46 Feature/back/route
  backend/controllers/plant.controller.js
  backend/models/index.js
  backend/models/plant.model.js
  backend/routes/plants.route.js
Labels: BE, enhancement

#44 add Dockerfile to build backend app
  backend/.dockerignore
  backend/Dockerfile
Labels: BE, enhancement

#47 [refactor] refactoring controller logic
  backend/controllers/plant.controller.js
  backend/routes/plants.route.js
Labels: BE, enhancement

#49 keyword search & view count logic refactoring
  backend/controllers/plant.controller.js
  backend/routes/plants.route.js
Labels: BE, enhancement

#48 [feat] add docker-compose for deploying backend
  backend/.dockerignore
  backend/config/config.js
  backend/docker-compose.yml
  backend/nginx.conf
Labels: BE, enhancement

#53 add sequelize import statement in plant.cotronller.js
  backend/controllers/plant.controller.js
Labels: BE, bug

#54 Feature/front/test main
  frontend/public/images/test_start.png
  frontend/src/App.tsx
  frontend/src/components/Section.jsx
  frontend/src/components/TestMain.jsx
  frontend/src/lib/calculate.js
  frontend/src/styles/Button.js
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/theme.js
  frontend/src/views/Home.jsx
  frontend/src/views/TestStart.jsx
Labels: FE, enhancement

#56 Feature/front/modify footer style
  frontend/src/components/Footer/Contact.jsx
  frontend/src/components/Footer/Corp.jsx
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/Item.jsx
  frontend/src/styles/FooterItem.js
  frontend/src/styles/theme.js
Labels: FE

#51 태그 검색 기능 (태그를 검색하여 해당 태그를 갖고있는 식물 정보를 리턴
  backend/app.js
  backend/controllers/tag.controller.js
  backend/routes/tags.route.js
  backend/search.json
Labels: BE, enhancement

#55 tagSearch
  backend/app.js
  backend/controllers/plant.controller.js
  backend/package.json
  backend/routes/plants.route.js
Labels: BE, enhancement

#57 ScrollTop button 추가
  frontend/public/images/top_button.png
  frontend/src/App.tsx
  frontend/src/components/ScrollTop.jsx
  frontend/src/styles/theme.js
Labels: FE, enhancement

#63 기존 컴포넌트 사이즈 대응 전체적으로 수정
  frontend/public/images/bg_home.png
  frontend/src/components/Section.jsx
  frontend/src/components/TestMain.jsx
  frontend/src/lib/calculate.js
  frontend/src/styles/Button.js
  frontend/src/styles/theme.js
Labels: FE

#64 [feat] add Main section in Home component
  frontend/public/images/arrow.png
  frontend/public/images/logo_home.png
  frontend/src/components/Home/Main.jsx
  frontend/src/styles/GlobalStyle.js
  frontend/src/views/Home.jsx
Labels: FE, TODO

#66 [feat] add type, description, imagePath in PlantTags junction table
  backend/controllers/plant.controller.js
  backend/models/plant.model.js
  backend/models/plantTag.model.js
  backend/models/tag.model.js
  backend/search.json
  backend/setup.js
Labels: BE, enhancement

#67 [chore] add cloudformation template with serveless frame work
  backend/deployment/README.md
  backend/deployment/imageBucket/serverless.yml
  backend/deployment/webBucket/severless.yml
Labels: BE, enhancement

#69 Feature/front/test
  frontend/public/images/test_path.svg
  frontend/src/components/Section.jsx
  frontend/src/components/TestQuestion.jsx
  frontend/src/const/testData.js
  frontend/src/styles/Button.js
  frontend/src/views/Test.jsx
  frontend/src/views/TestResult.jsx
Labels: FE, enhancement

#71 Feature/front/keyword search
  frontend/public/images/search.svg
  frontend/src/components/Home/KeywordSearch.jsx
  frontend/src/components/TagList.jsx
  frontend/src/styles/Button.js
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/SubHead.js
  frontend/src/styles/tagList.js
  frontend/src/styles/theme.js
  frontend/src/views/Home.jsx
Labels: FE, enhancement

#72 [feat] add document about jenkins for backup
  backend/jenkins/README.md
  backend/jenkins/back.groovy
  backend/jenkins/front.groovy
Labels: BE, enhancement

#75 Feature/front/test result
  frontend/package.json
  frontend/public/images/fb.svg
  frontend/public/images/kt.svg
  frontend/public/images/reset.svg
  frontend/public/images/right_arrow.svg
  frontend/public/images/save.svg
  frontend/public/images/share.svg
  frontend/public/images/url.svg
  frontend/src/components/Section.jsx
  frontend/src/views/TestResult.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#78 Feature/front/popular plants
  frontend/src/components/Home/PopularPlants.jsx
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/Section.jsx
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/recommentPlant.js
  frontend/src/styles/tagList.js
  frontend/src/views/Home.jsx
Labels: FE

#77 Feature/backend/add more setup data
  backend/setup.js
Labels: BE, enhancement

#70 [feat] add returning requested plant's all tag logic
  backend/controllers/plant.controller.js
Labels: BE, enhancement

#80 [refactor] remove timestamps in getListPlants logic's response
  backend/controllers/plant.controller.js
Labels: BE, enhancement

#81 [refactor] change plant's detail response
  backend/controllers/plant.controller.js
Labels: BE, enhancement

#84 나머지 식물 등록
  backend/setup.js
Labels: BE

#85 [feat] add swagger interface
  backend/app.js
  backend/package-lock.json
  backend/package.json
  backend/routes/plants.route.js
  backend/routes/swagger.route.js
Labels: BE, enhancement

#87 Fix/backend/search api
  backend/controllers/plant.controller.js
  backend/routes/plants.route.js
Labels: BE, TODO

#88 [chore] modfiy swagger document
  backend/routes/plants.route.js
Labels: BE, enhancement

#92 [feat] limit api call request count per ip
  backend/app.js
  backend/package-lock.json
  backend/package.json
Labels: BE, enhancement

#89 [chore] add swagger document for /tags api calls
  backend/controllers/tag.controller.js
  backend/models/tag.model.js
  backend/routes/tags.route.js
  backend/setup.js
Labels: BE, documentation, enhancement

#90 [feat] change response format.
  backend/setup.js
Labels: BE, enhancement

#91 [feat] add full size image path
  backend/setup.js
Labels: BE, enhancement

#93 [chore] change load balancing algorithm
  backend/docker-compose.yml
  backend/nginx.conf
Labels: BE, enhancement

#94 Feature/front/swiper
  frontend/package.json
  frontend/src/components/Home/PopularPlants.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#96 식물 상세 페이지 기본 컴포넌트 생성
  frontend/package.json
  frontend/public/images/detailTags/shade.svg
  frontend/public/images/detailTags/shade_md.svg
  frontend/public/images/flower.svg
  frontend/public/images/func.svg
  frontend/public/images/leaf.svg
  frontend/public/images/nothing_arrow.svg
  frontend/src/components/Nothing.jsx
  frontend/src/components/PlantsDetail/Feature.jsx
  frontend/src/components/PlantsDetail/FeatureCard.jsx
  frontend/src/components/PlantsDetail/TagCard.jsx
  frontend/src/components/PlantsDetail/TagsDetail.jsx
  frontend/src/components/PlantsDetail/Warning.jsx
  frontend/src/components/PlantsDetail/WarningCard.jsx
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/theme.js
  frontend/src/views/PlantsDetail.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#82 Feature/front/slider
  frontend/package.json
  frontend/src/components/Home/PopularPlants.jsx
  frontend/src/styles/GlobalStyle.js
  frontend/yarn.lock
Labels: FE, help wanted

#97 [refactor] change app.js as class
  backend/app.js
Labels: BE, enhancement

#100 상세 페이지 나머지 컴포넌트 추가
  frontend/src/components/Home/PopularPlants.jsx
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/PlantsDetail/Friends.jsx
  frontend/src/components/PlantsDetail/PlantMain.jsx
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/Slider.jsx
  frontend/src/components/TestQuestion.jsx
  frontend/src/const/sliderPlantsTest.js
  frontend/src/styles/Button.js
  frontend/src/styles/DescText.js
  frontend/src/views/PlantsDetail.jsx
  frontend/src/views/TestResult.jsx
Labels: FE, enhancement

#102 [feat] add '#' in 잎도촉촉히 Tag
  backend/setup.js
Labels: BE

#103 [refactor] remove thumbnail path in plant detail response
  backend/controllers/plant.controller.js
Labels: BE, enhancement

#105 [feat] add recommended plant response in detail plant api
  backend/controllers/plant.controller.js
Labels: BE, enhancement

#101 Feature/front/add func plants detail
  frontend/package.json
  frontend/public/images/detailTags/fast.svg
  frontend/public/images/detailTags/fast_md.svg
  frontend/public/images/detailTags/more_water.svg
  frontend/public/images/detailTags/more_water_md.svg
  frontend/public/images/detailTags/normal.svg
  frontend/public/images/detailTags/normal_md.svg
  frontend/public/images/detailTags/slow.svg
  frontend/public/images/detailTags/slow_md.svg
  frontend/public/images/detailTags/sunny.svg
  frontend/public/images/detailTags/sunny_md.svg
  frontend/public/images/detailTags/warmly.svg
  frontend/public/images/detailTags/warmly_md.svg
  frontend/public/images/detailTags/water.svg
  frontend/public/images/detailTags/water_md.svg
  frontend/public/images/featureCard/flower.svg
  frontend/public/images/featureCard/flower_md.svg
  frontend/public/images/featureCard/func.svg
  frontend/public/images/featureCard/func_md.svg
  frontend/public/images/featureCard/leaf.svg
  frontend/public/images/featureCard/leaf_md.svg
  frontend/src/api/instance.js
  frontend/src/api/plantsAPI.js
  frontend/src/components/Home/KeywordSearch.jsx
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/PlantsDetail/Feature.jsx
  frontend/src/components/PlantsDetail/FeatureCard.jsx
  frontend/src/components/PlantsDetail/Friends.jsx
  frontend/src/components/PlantsDetail/PlantMain.jsx
  frontend/src/components/PlantsDetail/TagCard.jsx
  frontend/src/components/PlantsDetail/TagsDetail.jsx
  frontend/src/components/PlantsDetail/Warning.jsx
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/Slider.jsx
  frontend/src/components/TagList.jsx
  frontend/src/components/TestMain.jsx
  frontend/src/const/config.js
  frontend/src/const/detailTags.js
  frontend/src/const/featureCard.js
  frontend/src/const/sliderPlantsTest.js
  frontend/src/const/tags.js
  frontend/src/lib/handler.js
  frontend/src/views/PlantsDetail.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#108 [chore] add .env file & adding that file in frontend/ directory
  backend/jenkins/front.groovy
Labels: BE, enhancement

#109 메인 페이지 기능, 데이터 추가
  frontend/package.json
  frontend/public/images/test_start.png
  frontend/src/api/plantsAPI.js
  frontend/src/components/Home/PopularPlants.jsx
  frontend/src/components/LottieImg.jsx
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/TestMain.jsx
  frontend/src/lottie/test_main.json
  frontend/src/views/PlantsDetail.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#110 정적 리소스를 S3 버킷에 자동 저장 및 배포하는 로직 추가. (이미지, 텍스트, json 등 모든 리소스 저장 가능)
  backend/jenkins/image.groovy
  readme.md
  resources/관음죽.png
  resources/관음죽_full.png
  resources/돈나무.png
  resources/돈나무_full.png
  resources/디시디아.png
  resources/디시디아_full.png
  resources/마리모.png
  resources/마리모_full.png
  resources/몬스테라.png
  resources/몬스테라_full.png
  resources/벵갈고무나무.png
  resources/벵갈고무나무_full.png
  resources/스킨답서스.png
  resources/스킨답서스_full.png
  resources/스투키.png
  resources/스투키_full.png
  resources/스파티필름.png
  resources/스파티필름_full.png
  resources/아레카야자.png
  resources/아레카야자_full.png
  resources/아이비.png
  resources/아이비_full.png
  resources/올리브나무.png
  resources/올리브나무_full.png
  resources/트리안.png
  resources/트리안_full.png
  resources/필레아페페.png
  resources/필레아페페_full.png
  resources/행운목.png
  resources/행운목_full.png
Labels: BE, enhancement

#116 [bugfix] modfiy wrong image path
  backend/setup.js
Labels: BE, bug

#115 [chore] add test load test logic with artillery
  backend/package.json
  backend/test.json
Labels: BE

#121 [feat] change some parameters in nginx.conf for enhancing
  backend/nginx.conf
Labels: BE, enhancement

#125 Feature/backend/change resource url
  backend/nginx.conf
  backend/routes/swagger.route.js
  backend/setup.js
Labels: BE, enhancement

#123 seperate controller to service layer
  backend/controllers/plant.controller.js
  backend/package-lock.json
  backend/package.json
  backend/services/plantService.js
Labels: BE

#128 /tags 결과를 정렬하여 보내는 로직
  backend/controllers/tag.controller.js
Labels: BE, enhancement

#126 [chore] add removing cache logic for cloudfront
  backend/jenkins/front.groovy
Labels: BE, enhancement

#132 [feat] add returning all tags while tag seraching
  backend/services/plantService.js
Labels: BE, enhancement, question

#130 Test/backend/api
  .gitignore
  backend/.prettierrc
  backend/app.js
  backend/config/config.js
  backend/controllers/auth.controller.js
  backend/controllers/index.controller.js
  backend/controllers/plant.controller.js
  backend/controllers/tag.controller.js
  backend/models/index.js
  backend/models/plant.model.js
  backend/models/plantTag.model.js
  backend/models/tag.model.js
  backend/models/user.model.js
  backend/package-lock.json
  backend/package.json
  backend/routes/auth.route.js
  backend/routes/index.route.js
  backend/routes/plants.route.js
  backend/routes/swagger.route.js
  backend/routes/tags.route.js
  backend/server.js
  backend/services/plantService.js
  backend/setup.js
  backend/test/plant.controller.test.js
  backend/test/plant.model.test.js
  backend/test/plantService.test.js
  backend/test/plantTag.model.test.js
  backend/test/tag.model.test.js
Labels: BE

#135 [chore] add image path in plant's tag
  backend/setup.js
Labels: BE, enhancement

#138 피그마 화면과 동일한 순서로 태그 정렬 추가 (누락된 태그 정렬 부분 모두 정리)
  backend/services/plantService.js
  backend/setup.js
Labels: BE, enhancement

#143 [bugfix]change image path in setup.js
  backend/setup.js
Labels: BE, bug

#139 식물 상세 정보 페이지 기능 추가 / 스타일 변경
  frontend/public/images/detailTags/fast.svg
  frontend/public/images/detailTags/fast_md.svg
  frontend/public/images/detailTags/more_water.svg
  frontend/public/images/detailTags/more_water_md.svg
  frontend/public/images/detailTags/normal.svg
  frontend/public/images/detailTags/normal_md.svg
  frontend/public/images/detailTags/shade.svg
  frontend/public/images/detailTags/shade_md.svg
  frontend/public/images/detailTags/slow.svg
  frontend/public/images/detailTags/slow_md.svg
  frontend/public/images/detailTags/sunny.svg
  frontend/public/images/detailTags/sunny_md.svg
  frontend/public/images/detailTags/warmly.svg
  frontend/public/images/detailTags/warmly_md.svg
  frontend/public/images/detailTags/water.svg
  frontend/public/images/detailTags/water_md.svg
  frontend/public/images/featureCard/flower.svg
  frontend/public/images/featureCard/flower_md.svg
  frontend/public/images/featureCard/func.svg
  frontend/public/images/featureCard/func_md.svg
  frontend/public/images/featureCard/leaf.svg
  frontend/public/images/featureCard/leaf_md.svg
  frontend/src/api/plantsAPI.js
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/PlantsDetail/Feature.jsx
  frontend/src/components/PlantsDetail/FeatureCard.jsx
  frontend/src/components/PlantsDetail/PlantMain.jsx
  frontend/src/components/PlantsDetail/TagCard.jsx
  frontend/src/components/PlantsDetail/TagsDetail.jsx
  frontend/src/components/PlantsDetail/Warning.jsx
  frontend/src/components/PlantsDetail/WarningCard.jsx
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/Slider.jsx
  frontend/src/components/TagList.jsx
  frontend/src/components/TestMain.jsx
  frontend/src/const/detailTags.js
  frontend/src/lib/handler.js
  frontend/src/styles/DescText.js
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/SubHead.js
  frontend/src/views/PlantsDetail.jsx
Labels: FE, enhancement

#147 cors policy
  backend/app.js
Labels: BE

#146 Feature/backend/cron job lambda for views ordering
  .gitignore
  backend/deployment/lambda/README.md
  backend/deployment/lambda/__init__.py
  backend/deployment/lambda/db.py
  backend/deployment/lambda/lmd_get_trigger.py
  backend/deployment/lambda/lmd_trigger.py
  backend/deployment/lambda/log.py
  backend/deployment/lambda/requirements.txt
  backend/deployment/lambda/serverless.yml
  backend/jenkins/lambda.groovy
  backend/models/plant.model.js
  backend/services/plantService.js
Labels: BE, enhancement

#152 [feat] change 잎도촉촉히 as 잎촉촉
  backend/setup.js
Labels: BE, enhancement

#155 sort tag
  backend/services/plantService.js
Labels: BE

#158 [feat] add group & having clause for filtering result
  backend/services/plantService.js
Labels: BE, bug, enhancement

#159 식물 도감 태그 검색 기능 추가
  frontend/package.json
  frontend/public/images/cancle.svg
  frontend/public/images/remove.svg
  frontend/public/images/remove_md.svg
  frontend/src/App.tsx
  frontend/src/components/Home/KeywordSearch.jsx
  frontend/src/components/Home/PopularPlants.jsx
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/RecommentPlant.jsx
  frontend/src/components/SearchPlants/ColorTags.jsx
  frontend/src/components/SearchPlants/FilteringTags.jsx
  frontend/src/components/SearchPlants/PlantList.jsx
  frontend/src/components/TagList.jsx
  frontend/src/const/tags.js
  frontend/src/lib/handler.js
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/recommentPlant.js
  frontend/src/styles/tagList.js
  frontend/src/styles/theme.js
  frontend/src/views/Home.jsx
  frontend/src/views/SearchPlant.jsx
  frontend/yarn.lock
Labels: FE, enhancement

#166 API 서버 부하테스트 타겟서버 수정 및 NGINX 로드밸런스 방식 변경
  backend/nginx.conf
  backend/test.json
Labels: BE, enhancement

#168 키워드 기반 식물 검색시 응답에 있는 식물 순서를 최근 조회수 기반으로 정렬
  backend/services/plantService.js
Labels: BE, enhancement

#170 추천 식물 리스트 정렬 로직 반영
  backend/services/plantService.js
Labels: BE, enhancement

#167 Feature/front/change home styles
  frontend/public/images/bg_home.png
  frontend/public/images/logo_footer.png
  frontend/public/images/logo_footer.svg
  frontend/public/images/logo_home.png
  frontend/public/images/logo_home.svg
  frontend/public/images/scroll_top.svg
  frontend/public/images/top_button.png
  frontend/src/components/Footer/Corp.jsx
  frontend/src/components/Home/KeywordSearch.jsx
  frontend/src/components/Home/Main.jsx
  frontend/src/components/ScrollTop.jsx
  frontend/src/components/Section.jsx
  frontend/src/components/Slider.jsx
  frontend/src/components/TestQuestion.jsx
  frontend/src/styles/SubHead.js
  frontend/src/views/Home.jsx
Labels: FE

#172 [feat]update plant's view every 12hours
  backend/deployment/lambda/serverless.yml
Labels: BE, enhancement

#176 Feature/front/add other features
  frontend/public/favicon.png
  frontend/public/images/search_arrow.svg
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/api/plantsAPI.js
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/PlantsDetail/PlantMain.jsx
  frontend/src/components/SearchPlants/FilteringTags.jsx
  frontend/src/components/Section.jsx
  frontend/src/components/Slider.jsx
  frontend/src/components/TestQuestion.jsx
  frontend/src/const/testData.js
  frontend/src/views/Error.jsx
  frontend/src/views/PlantsDetail.jsx
  frontend/src/views/TestResult.jsx
Labels: FE, enhancement

#174 테스트 식물 응답에 testDescription 응답 추가
  backend/models/plant.model.js
  backend/services/plantService.js
  backend/setup.js
Labels: BE, enhancement

#180 Feature/front/change lottie
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/Footer/Corp.jsx
  frontend/src/components/Home/KeywordSearch.jsx
  frontend/src/components/LottieImg.jsx
  frontend/src/components/LottiePlayer.jsx
  frontend/src/components/Nav/Nav.jsx
  frontend/src/components/SearchPlants/NoResult.jsx
  frontend/src/components/SearchPlants/PlantList.jsx
  frontend/src/components/TestMain.jsx
  frontend/src/lottie/test_loading.json
  frontend/src/lottie/test_main.json
  frontend/src/views/Home.jsx
  frontend/src/views/SearchPlant.jsx
  frontend/src/views/TestResult.jsx
  frontend/src/views/TestStart.jsx
  frontend/yarn.lock
Labels: FE

#191 Feature/front/add default meta tag
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/meta.png
Labels: FE

#196 프론트엔드 API 테스트 코드 작성
  frontend/src/test/plantAPI.test.js
Labels: FE, enhancement

#198 [chore] add logic removing objects in s3
  backend/jenkins/front.groovy
Labels: BE, bug, enhancement

#194 Feature/front/modify lottie
  frontend/public/index.html
  frontend/public/meta.png
  frontend/src/components/SearchPlants/SearchResultPlant.jsx
  frontend/src/components/TagList.jsx
  frontend/src/components/TestQuestion.jsx
  frontend/src/const/sliderPlantsTest.js
  frontend/src/const/tags.js
  frontend/src/views/TestResult.jsx
Labels: FE, enhancement

#202 Create LICENSE
  LICENSE
Labels: documentation

#204 테스트 결과 카카오 공유 기능
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/TagList.jsx
  frontend/src/const/config.js
  frontend/src/lib/initialize.js
  frontend/src/lib/share.js
  frontend/src/views/TestResult.jsx
Labels: FE, bug, enhancement

#206 발표 전 최종 수정 사항 반영
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/PlantsDetail/AllKeywords.jsx
  frontend/src/components/SearchPlants/SearchResultPlant.jsx
  frontend/src/components/TagList.jsx
  frontend/src/const/config.js
  frontend/src/lib/initialize.js
  frontend/src/lib/share.js
  frontend/src/views/TestResult.jsx
Labels: FE, bug, enhancement
